data:
  dataset_path: data/fmnist
  in_channels: 1
  len_test: 10000
  len_train: 60000
  log_path: 
      pt: darts_pt/log
      tf: darts_tf/log
      pp: darts_pp/log
  out_channels: 10
  preprocessed: data/fmnist/preprocessed.h5
  seed: 0
  img_size: 28
search:
  batchsize: 40
  best_geno_count: 40
  cv_file: data/fmnist/cv_search.pkl
  depth: 8
  epochs: 200
  geno_file: best_genotype.pkl
  init_node_c: 16
  last_save: search_last
  last_aux: search_last_aux.pkl # for paddlepaddle
  n_fold: 2
  n_nodes: 4
train:
  batchsize: 40
  best_shot: train_best
  best_aux: train_best_aux.pkl # for paddlepaddle
  cv_file: data/fmnist/cv_train.pkl
  last_save: train_last
  last_aux: train_last_aux.pkl # for paddlepaddle
  n_fold: 5
  drop_rate: 0.2
  epochs: 200
test:
  batchsize: 200
